# Use the latest 2.1 version of CircleCI pipeline processing engine
version: 2.1
executors:
  default:
    docker: # run the steps with Docker
      - image: cimg/node:16.1-browsers
        environment:
          # this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

jobs: # a collection of steps
  prepare:
    executor: default
    steps: # a collection of executable commands
      - run:
          name: Running in a Unique Container
          command: |
            node -v
            npm -v

      # - run:
      #     name: Updating npm at latest
      #     command: |
      #       'sudo npm install -g npm@latest'
      #       npm -v

  build: # runs not using Workflows must have a `build` job as entry point
    executor: default
    steps:
      - restore_cache:
          keys:
            - source-v3-{{ .Branch }}-{{ .Revision }}
            - source-v3-{{ .Branch }}-
            - source-v3-

      - checkout # special step to check out source code to working directory

      - run:
          name: Source Code has arrived ✨
          command: |
            ls -al
            echo 'The working directory after check out source code'
      - run:
          name: Loading environment variables
          command: bash ./deploy_config.sh
      - run:
          name: Running git garbage collection
          command: git gc

      - save_cache:
          key: source-v3-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache: # special step to restore the dependency cache
          keys:
            - v9-node-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v9-node-dependencies-{{ .Branch }}
            - v9-node-dependencies-

      - run:
          name: Print cached NPM modules size
          command: du -d 0 -h ~/.npm || true
      - run:
          name: Installing Dependencies 📦
          command: npm ci
      # - run:
      #     name: Print NPM cache directory
      #     command: npm config get cache
      - run:
          name: Print NPM modules after install
          command: du -d 0 -h ~/.npm || true
      - run:
          name: Verifying Cypress 🌲
          command: npm run cy:verify

      - save_cache: # special step to save the dependency cache
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - node_modules
            #- functions/node_modules
            - ~/.npm
            - ~/.cache
          key: v9-node-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # when passing files to run the app and the tests
      # we do NOT need the NPM cache since everything has been installed already
      - run: rm -rf .npm

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .
      # - persist_to_workspace:
      #     root: /home/circleci
      #     paths:
      #       - .
      - run:
          name: Finally the working directory after build steps
          command: |
            ls -al
            echo 'The working directory after build steps'
  test:
    executor: default
    parallelism: 1
    steps:
      - attach_workspace:
          at: /home/circleci

      # - run:
      #     name: Split tests glob pattern
      #     command: |
      #       echo $(circleci tests glob "src/app/*.spec.ts" "src/app/auth/**/*.spec.ts" "src/app/**/*[!service].spec.ts")
      #       circleci tests glob "src/app/*.spec.ts" "src/app/auth/**/*.spec.ts" "src/app/**/*[!service].spec.ts" | xargs -n 1 echo
      - run:
          name: Running Unit Tests with Jest and collecting coverage reports for Coveralls 🧪
          command: npm run test:cov
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage
          destination: coverage
      - run:
          name: Finally the working directory after unit tests steps
          command: |
            ls -al
            echo 'The working directory after Jest Unit Tests'

  test_e2e:
    executor: default
    parallelism: 1
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Running End-to-End Tests and recording with Cypress 🧪
          command: npm run e2e:ci

      # - store_test_results:
      #     path: ./cypress-coverage
      # - store_artifacts:
      #     path: ./cypress-coverage
      #     destination: cypress-coverage
      # # print code coverage summary to the terminal
      # - run: npm run cov:report

      # - persist_to_workspace:
      #     root: /home/circleci
      #     paths: .

      - run:
          name: Finally the working directory after e2e test steps
          command: |
            ls -al
            echo 'The working directory after e2e test'

  test_e2e_staging:
    executor: default
    parallelism: 3
    steps:
      - attach_workspace:
          at: /home/circleci
      # runs Cypress test in load balancing (parallel) mode
      # and groups them in Cypress Dashboard under name "electron-3x"
      - run:
          name: Running End-to-End Tests and recording with Cypress in Staging mode 🧪
          command: npm run e2e:ci:staging

      #- store_test_results:
      #    path: e2e-results
      # - store_artifacts:
      #     path: cypress/videos
      # - store_artifacts:
      #     path: cypress/screenshots
      # - store_test_results:
      #     path: ./cypress-coverage
      # - store_artifacts:
      #     path: ./cypress-coverage
      #     destination: cypress-coverage
      # # print code coverage summary to the terminal
      # - run: npm run cov:report

      # - persist_to_workspace:
      #     root: /home/circleci
      #     paths: .

      - run:
          name: Finally the working directory after e2e test step in Staging mode
          command: |
            ls -al
            echo 'The working directory after e2e test step'

  deploy_staging:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Building branch to staging
          command: npm run build:staging
      - run:
          name: Deploying branch to Firebase staging hosting 🎉
          command: |
            ./node_modules/.bin/firebase deploy -m "Staging deployed with CircleCI." \
            --only hosting \
            --project $FIREBASE_STAGING_PROJECT_ID \
            --token=$FIREBASE_DEPLOY_TOKEN

  deploy_production:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Building main to production
          command: npm run build:prod

      - run:
          name: Deploying main to Firebase 🚀
          command: |
            ./node_modules/.bin/firebase deploy -m "Deployed with CircleCI." \
            --only hosting \
            --project $FIREBASE_PROJECT_ALIAS \
            --token=$FIREBASE_DEPLOY_TOKEN

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build_test: # This workflow will run on 'main' and will not run on tags
    jobs:
      - prepare:
          filters: &filters-pre-prod
            branches:
              only:
                - main
                - /release-.*/
                - /docs-.*/
            tags:
              ignore: /.*/
      - build:
          requires:
            - prepare
          filters:
            <<: *filters-pre-prod
      - test:
          requires:
            - build
          filters:
            <<: *filters-pre-prod

  staging: # This workflow will only run on 'dev' and will not run on tags
    jobs:
      - prepare:
          filters: &filters-staging # this yaml anchor is setting these values to "filters-staging"
            branches:
              only:
                - develop
                - next
                - /feature-.*/
                - /issue-.*/
                - /bugfix-.*/
                - /hotfix-.*/
                - /chore-.*/
                - /perf-.*/
                - /patch-.*/
                - /dependabot/.*/
                - /experiment-.*/
            tags:
              ignore: /.*/
      - build:
          requires:
            - prepare
          filters:
            <<: *filters-staging # this is calling the previously set yaml anchor
      - test:
          requires:
            - build
          filters:
            <<: *filters-staging
      - test_e2e_staging:
          requires:
            - test
          filters:
            <<: *filters-staging
      - deploy_staging:
          requires:
            - test_e2e_staging
          filters:
            branches:
              only:
                - develop
            tags:
              ignore: /.*/

  production: # This workflow will only run on tags (specifically starting with 'v.') and will not run on branches
    jobs:
      - prepare:
          filters: &filters-production # this yaml anchor is setting these values to "filters-production"
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - build:
          requires:
            - prepare
          filters:
            <<: *filters-production
      - test:
          requires:
            - build
          filters:
            <<: *filters-production
      - hold_approval: # A job that will require manual approval in the CircleCI web application.
          type: approval # This key-value pair will set my workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test has succeeded
            - test
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
      # On approval of the `hold` job, any successive job that requires the `hold` job will run.
      # In this case, a user is manually triggering the deploy job.
      - deploy_production:
          requires:
            - hold_approval
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
